 
//Array of 50 students
// let Students = [];
let Student= [{name:"Sushree" ,age:21,
    batch:"MCA",
    Roll_no:145 }][{name:"Jayashree", age:21,
    batch:"MCA",
    Roll_no:145 , name:"Romi", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Sasmita", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Sonali" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Sudikshya" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Banita" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Pallavi" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Bhagyalaxmi", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"DadhiPriya" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:" Lipsa" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Anshita", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Nilima", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Diksha" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Sonitashree" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Madhusmita", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Somalin", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Gayatri" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Abhipsa", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Deepali", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Lopa", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Shakti", age:21,
    batch:"MCA",
    Roll_no:145,name:"Alisha", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Prateekshya", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Rupali" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Tanisa" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Soumya" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Deepsikha", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Bhagyashree" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Sonita" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Susmita", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Sonalika", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Subhalaxmi", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Monali" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Monalisha", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Suchismita" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Smruti" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Yangyasini" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Payal", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Monita", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Sparky", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Krishna" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Subha" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Mahi", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Rojalin", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Janklin", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Jyoti", age:21,
    batch:"MCA",
    Roll_no:145,name:"liki" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Snigdha", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Suprava" ,age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Swagatika", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Miki", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Rasmita", age:21,
    batch:"MCA",
    Roll_no:145 ,name:"Satty" ,age:21,
    batch:"MCA",
    Roll_no:145 ,
    age:21,
    batch:"MCA",
    Roll_no:145 ,
}]
// for (let i =0;i<= 50;i++){
// Student.forEach((element,j) =>{
// console.log(element);
// });
// }
// let students = [
//     { name: "Sushree", age: 21, batch: "MCA", Roll_no: 145 },
//     { name: "John", age: 21, batch: "MCA", Roll_no: 146 },
//     { name: "Jane", age: 22, batch: "MBA", Roll_no: 147 },
//     { name: "Alice", age: 21, batch: "MCA", Roll_no: 148 }
// ];

// // Starting roll number
// let startingRollNo = 150;

// // Update roll numbers serially
// students.forEach((student, index) => {
//     student.Roll_no = startingRollNo + index; // Increment roll number based on index
// });

// // Log the updated students array
// console.log(students);


